### ISSUE TITLE
issue trying to run a test

### ISSUE THREAD

**Issue by marina-manrique** [era7bio/bundles#16]
I'm getting this error when I try to run a test
```bash
[info] - testing Velvet *** FAILED ***
[info]   com.amazonaws.AmazonServiceException: The image id '[ami-75b2d356]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: f24d1c08-9170-459b-87f4-b4def4aa7cdc)
[info]   at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1078)
[info]   at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:726)
[info]   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
[info]   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
[info]   at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:10549)
[info]   at com.amazonaws.services.ec2.AmazonEC2Client.runInstances(AmazonEC2Client.java:4987)
[info]   at ohnosequences.awstools.ec2.EC2.runInstances(EC2.scala:295)
[info]   at era7.bundles.tests.ApplicationTest.launchAndWait(Tests.scala:32)
[info]   at era7.bundles.tests.ApplicationTest$$anonfun$1.apply$mcV$sp(Tests.scala:71)
[info]   at era7.bundles.tests.ApplicationTest$$anonfun$1.apply(Tests.scala:61)
```
@eparejatobes @laughedelic any idea?

**Comment by laughedelic** [comment]
yep, my fault. forgot to update aws-statika. 1 minute

**Comment by marina-manrique** [comment]
:+1:

**Comment by laughedelic** [comment]
done. just do `sbt update`

**Comment by laughedelic** [comment]
ah, and if you're testing, re-publish before running the test

**Comment by marina-manrique** [comment]
Ok thanks!

**Comment by marina-manrique** [comment]
it works, closing this
